#!/usr/bin/env bash
# FizzBuzz test

for ((i = 1; i < 101; i++ )); do
	fizz=$(("$i" % 3))
	buzz=$(("$i" % 5))
	if [ "$fizz" -eq 0 ] && [ "$buzz" -eq 0 ];
	then
		echo "FizzBuzz"
	elif [ "$fizz" -eq 0 ];
	then
		echo "Fizz"
	elif [ "$buzz"  -eq 0 ];
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
